### ISSUE TITLE
Vision for 0.1

### ISSUE THREAD

**Issue by LucioFranco** [LucioFranco/amethyst-protocol#6]
This issue refers to the goals of the project for version `0.1.0`.

Goals for `0.1.0`:
- [ ] Semi reliable packets
- [ ] Congestion avoidance ([issue](https://github.com/LucioFranco/amethyst-protocol/issues/4))
- [ ] Ability to send large packets ([issue](https://github.com/LucioFranco/amethyst-protocol/issues/5))
- [ ] Ability to send events up to the application, such as Client Connected, Client Disconnected ([issue](https://github.com/LucioFranco/amethyst-protocol/issues/8))
- [x] Regular check of all connected clients to see if they have timed out ([issue](https://github.com/LucioFranco/amethyst-protocol/issues/7))
- [ ] Option to create a pure TCP server if the developer wants a truly reliable connection ([issue](https://github.com/LucioFranco/amethyst-protocol/issues/9))
- [x] Create enum for connection events ([issue](https://github.com/LucioFranco/amethyst-protocol/issues/10))
- [ ] Add protocol identifier ([issue](https://github.com/LucioFranco/amethyst-protocol/issues/11))
- [ ] Add example usage ([issue](https://github.com/LucioFranco/amethyst-protocol/issues/#13 ))

**Comment by LucioFranco** [comment]
Closing this issue as we should refer to the `0.1.0` milestone instead.
